// Phrase categories as mentioned in the game rules
export enum PhraseCategory {
  EVERYTHING = 'Everything',
  EVERYTHING_PLUS = 'Everything+',
  MOVIES = 'Movies & TV',
  MUSIC = 'Music & Artists',
  SPORTS = 'Sports & Athletes',
  FOOD = 'Food & Drink',
  PLACES = 'Places & Travel',
  PEOPLE = 'Famous People',
  TECHNOLOGY = 'Technology & Science',
  HISTORY = 'History & Events',
  ENTERTAINMENT = 'Entertainment & Pop Culture',
  NATURE = 'Nature & Animals'
}

// High-quality generated phrases for each category
const moviePhrases = [
  "Friends Sitcom",
  "Darth Vader",
  "Time Travel",
  "Alien Spaceship",
  "Friends TV Show",
  "Mission Impossible",
  "Iron Man Suit",
  "Lightsaber Battle",
  "Batman Begins",
  "Batman Returns",
  "Wonder Woman",
  "The Simpsons",
  "Batmobile Chase",
  "The Crown",
  "Harry Potter",
  "Vampire Slayer",
  "Avatar The Movie",
  "Frozen Snowman",
  "The Matrix",
  "Avatar Movie",
  "The Lion King",
  "Oscar Ceremony",
  "Lord of Rings",
  "Fast and Furious",
  "The Batmobile",
  "Star Trek",
  "Friends Reunion",
  "Sherlock Holmes",
  "Titanic Movie",
  "Spider-Man Swing",
  "Captain Jack Sparrow",
  "The Godfather",
  "Magic Carpet Ride",
  "Frozen Disney",
  "James Bond",
  "Black Panther",
  "The Office",
  "Toy Story",
  "Netflix Binge-Watch",
  "The Avengers",
  "Shrek Swamp",
  "Captain America",
  "The Mandalorian",
  "Hunger Games",
  "Hollywood Movie Set",
  "Avengers Assemble",
  "Lightsaber Duel",
  "Jurassic Park",
  "Zombie Apocalypse",
  "Wakanda Forever",
  "Jedi Knight",
  "Iron Man",
  "Superhero Landing",
  "Reality Show Drama",
  "Pizza Delivery",
  "Central Perk",
  "Game of Thrones",
  "Breaking Bad",
  "Paw Patrol",
  "Sitcom Laugh Track",
  "Stranger Things",
  "Animated Feature",
  "Simpsons Family",
  "Frozen Sing-Along",
  "Red Carpet Walk",
  "Romantic Comedy",
];

const entertainmentPhrases = [
  "Grammys Night",
  "Kardashian Family",
  "Hollywood Red Carpet",
  "Oscar Acceptance",
  "Broadway Musical",
  "TikTok Dance",
  "Squid Game",
  "Fantasy Novel",
  "Super Mario",
  "Marvel Movies",
  "Streaming Service",
  "Beyonce Concert",
  "The Weeknd",
  "Mickey Mouse",
  "Billie Eilish",
  "Reality TV",
  "Frozen Movie",
  "Oscar Statue",
  "Netflix Binge",
  "Binge Watching",
  "TikTok Dances",
  "Celebrity Gossip",
  "Super Bowl",
  "Marvel Avengers",
  "Comic Con",
  "Avengers Movie",
  "Kardashian Drama",
  "Karaoke Night",
  "YouTube Channel",
  "Mario Kart",
  "Oscar Nominee",
  "Video Game Streamer",
  "Red Carpet",
  "Harry Styles",
  "Disneyland Trip",
  "Marvel Superhero",
  "Action Figure",
  "TikTok Challenge",
  "Avengers Endgame",
  "Superhero Movie",
  "Reality TV Show",
  "Instagram Influencer",
  "Oscar Night",
  "Reality Show",
  "Video Game",
  "YouTube Star",
  "Marvel Comics",
  "Blockbuster Hit",
  "K-Pop Dance",
  "Pop Concert",
  "Marvel Universe",
  "Hollywood Walk",
  "K-Pop Band",
  "Broadway Show",
  "Disney Princess",
  "Disney World",
  "Grammy Winner",
  "Netflix Series",
  "Oscar Winner",
  "TikTok Trends",
  "Streaming Platform",
  "Pop Music",
  "Popcorn Movie",
];

const musicPhrases = [
  "Jazz Band",
  "Rock Band",
  "Beyoncé Performance",
  "Piano Lesson",
  "Guitar Solo",
  "Drake Album",
  "Kanye West",
  "Adele Song",
  "Rap Battle",
  "Piano Keys",
  "Backstreet Boys",
  "Piano Solo",
  "Rock Festival",
  "Country Music",
  "Jazz Festival",
  "K-Pop Idol",
  "Katy Perry",
  "Singing In Shower",
  "Hip Hop Dance",
  "Jazz Singer",
  "Elton John",
  "Guitar Hero",
  "Hip Hop",
  "Playing Drums",
  "Beyoncé Concert",
  "Justin Bieber",
  "Rock Concert",
  "DJ Mixer",
  "Beatles Reunion",
  "Violin Concerto",
  "Classical Symphony",
  "Saxophone Solo",
  "Michael Jackson",
  "Violin Symphony",
  "Music Festival",
  "Drum Solo",
  "Piano Man",
  "Choir Singing",
  "Violin Strings",
  "Piano Recital",
  "Violin Concert",
  "Piano Concerto",
  "Ed Sheeran",
  "Rock Star",
  "Taylor Swift",
  "Adele Concert",
  "Lady Gaga",
  "Violin Solo",
  "Singing in Shower",
  "Beyonce Knowles",
  "Elvis Presley",
  "Drum Kit",
  "Saxophone Player",
  "Pop Idol",
  "Bob Dylan",
  "Beyoncé Dance",
  "The Beatles",
  "Opera Singer",
  "Pop Star",
  "Drum Set",
  "Electric Guitar",
];

const placesPhrases = [
  "London Bridge",
  "Alaskan Cruise",
  "Theme Park",
  "Train Journey",
  "Mountain Hike",
  "Tokyo Subway",
  "Ancient Pyramids",
  "Venice Canals",
  "Backpacking Trip",
  "City Tour",
  "Island Hop",
  "Airport Check-In",
  "Travel Backpack",
  "Sydney Opera House",
  "Cruise Ship",
  "Tokyo Disneyland",
  "Hiking Trail",
  "Beach Resort",
  "Tropical Island",
  "Grand Canyon",
  "Roadside Motel",
  "Tourist Guide",
  "Great Wall of China",
  "Bungee Jumping",
  "Great Wall",
  "Road Trip",
  "Airplane Boarding",
  "Tropical Beach",
  "Rome Colosseum",
  "Camping Trip",
  "Paris Eiffel Tower",
  "Mount Everest",
  "Backpacking Journey",
  "Backpacking Europe",
  "Luxury Hotel",
  "New York City",
  "Beach Vacation",
  "Eiffel Tower",
  "Camping Site",
  "Amazon Rainforest",
  "Niagara Falls",
  "Santorini Sunset",
  "Hawaiian Luau",
  "Jungle Trek",
  "Times Square",
  "Venice Gondola",
  "Hotel Check-In",
  "Desert Safari",
  "Passport Control",
  "Airport Security",
  "Train Station",
  "Safari Adventure",
];

const naturePhrases = [
  "Lion Roaring",
  "Tropical Rain",
  "Busy Beehive",
  "Mountain Peak",
  "Running Cheetah",
  "Honey Bee",
  "Forest Fire",
  "Elephant Herd",
  "Rainforest Canopy",
  "Bird Migration",
  "Cherry Blossom",
  "Kangaroo Jumping",
  "Dolphin Jump",
  "Blooming Flowers",
  "Roaring Lion",
  "Flying Squirrel",
  "Butterfly Flutter",
  "Climbing Trees",
  "Beaver Dam",
  "Penguin Waddle",
  "Giraffe Neck",
  "Ocean Waves",
  "Jungle Safari",
  "Giraffe Eating",
  "Lion Roar",
  "Bird Watching",
  "Snowy Owl",
  "Dolphin Dance",
  "Bear Hibernation",
  "Beehive Buzzing",
  "Desert Cactus",
  "Eagle Soaring",
  "Butterfly Garden",
  "Desert Oasis",
  "Tropical Rainforest",
  "Volcano Eruption",
  "Misty Mountains",
  "Mountain Climb",
  "Forest Trail",
  "Sunflower Field",
  "Sunset Horizon",
  "Kangaroo Jump",
  "Swimming Dolphins",
  "Whale Breaching",
  "Coral Reef",
  "Forest Hike",
  "Polar Bear",
  "Elephant Trunk",
];

const techPhrases = [
  "Bluetooth Headphones",
  "Voice Assistant",
  "Space Shuttle",
  "Solar Panel",
  "Smartphone Selfie",
  "Bluetooth Speaker",
  "Social Media",
  "Space Rocket",
  "Drone Delivery",
  "Cyber Security",
  "Solar Panels",
  "Space Station",
  "WiFi Signal",
  "Mars Rover",
  "Virtual Reality",
  "Wi-Fi Password",
  "Space Travel",
  "Smart Home",
  "Smart Watch",
  "Augmented Reality",
  "DNA Testing",
  "Electric Scooter",
  "Video Call",
  "Smartphone App",
  "3D Printing",
  "3D Printer",
  "Space Telescope",
  "Wireless Charger",
  "Drone Camera",
  "Streaming Video",
  "Self-driving Car",
  "Digital Camera",
  "Solar Energy",
  "Internet Browser",
  "Self-Driving Car",
  "Wireless Charging",
  "Online Shopping",
  "Robot Vacuum",
  "Cloud Computing",
  "Smart Speaker",
  "Rocket Launch",
  "Electric Car",
  "DNA Test",
  "Cloud Storage",
  "Wireless Headphones",
  "Quantum Computer",
  "DNA Sequencing",
  "Robotic Vacuum",
];

const sportsPhrases = [
  "Lionel Messi",
  "Hockey Puck",
  "Serena Williams",
  "Swimming Laps",
  "Rugby Scrum",
  "Penalty Kick",
  "Cricket Batting",
  "Usain Bolt",
  "Home Run",
  "Boxing Match",
  "Gymnastics Routine",
  "Olympic Gold Medal",
  "Rafael Nadal",
  "Swimming Relay",
  "Swimming Race",
  "Football Touchdown",
  "Marathon Runner",
  "Cycling Race",
  "Baseball Pitcher",
  "Cricket Bat",
  "Volleyball Spike",
  "Soccer Goalie",
  "Gymnastics Flip",
  "Ice Hockey",
  "Formula One",
  "Soccer Goal",
  "Baseball Home Run",
  "Swimming Lap",
  "Olympic Medal",
  "Tiger Woods",
  "Rugby Tackle",
  "Tom Brady",
  "Soccer Penalty",
  "Figure Skating",
  "Olympic Torch",
  "Olympic Gold",
  "Fencing Duel",
  "Skateboarding Trick",
  "Baseball Pitch",
  "Running Marathon",
  "Tennis Serve",
  "Golf Swing",
  "Basketball Dunk",
  "World Cup",
  "Football Tackle",
  "Simone Biles",
];

const historyPhrases = [
  "Falling Berlin Wall",
  "Gold Rush",
  "Alexander the Great",
  "Martin Luther King",
  "Titanic Sinking",
  "Mona Lisa Stolen",
  "Sinking Lusitania",
  "D-Day Invasion",
  "Magna Carta Signing",
  "Fall of Rome",
  "Golden Gate Opens",
  "Gettysburg Address",
  "Mount Rushmore",
  "Signing Declaration",
  "Pearl Harbor Attack",
  "Stone Age",
  "Woodstock Festival",
  "Great Depression",
  "Roswell UFO Incident",
  "Black Plague",
  "Moon Landing",
  "Great Wall China",
  "Berlin Wall Fall",
  "Fall of Berlin Wall",
  "Berlin Wall Falls",
  "Renaissance Period",
  "Rosa Parks Bus",
  "Berlin Wall",
  "Maya Civilization",
  "Ancient Egypt",
  "Women Voting",
  "Boston Tea Party",
  "Civil Rights March",
  "First Flight",
  "Fall Of Berlin Wall",
  "Women's Suffrage",
  "Titanic Sinks",
  "Great Wall Built",
  "Renaissance Art",
  "Olympic Games",
  "American Revolution",
  "Pearl Harbor",
  "French Revolution",
];

const foodPhrases = [
  "Hot Chocolate",
  "Pancake Stack",
  "Hamburger Feast",
  "Caesar Salad",
  "Coffee Break",
  "Green Tea",
  "Spaghetti and Meatballs",
  "Pizza Party",
  "Lemonade Stand",
  "Cappuccino Foam",
  "Cheese Burger",
  "Banana Split",
  "Milkshake Straw",
  "Fruit Smoothie",
  "Pancake Breakfast",
  "Chocolate Cake",
  "Popcorn Bucket",
  "Pumpkin Spice Latte",
  "BBQ Ribs",
  "Taco Tuesday",
  "Pineapple Pizza",
  "Margarita Pizza",
  "Mashed Potatoes",
  "French Fries",
  "Ice Cream Cone",
  "Garlic Bread",
  "Apple Pie",
  "Hot Dog Stand",
  "Sushi Roll",
  "Chicken Nuggets",
  "Spaghetti Dinner",
  "Taco Fiesta",
  "Popcorn Snack",
  "Ice Cream",
  "Tea Time",
  "Watermelon Slice",
];

const peoplePhrases = [
  "Donald Trump",
  "Bill Gates",
  "Jennifer Aniston",
  "Nelson Mandela",
  "Prince Harry",
  "Oprah Winfrey",
  "William Shakespeare",
  "Marilyn Monroe",
  "Queen Elizabeth",
  "Emma Watson",
  "Leonardo DiCaprio",
  "Jennifer Lopez",
  "Elon Musk",
  "Chris Hemsworth",
  "Kim Kardashian",
  "Ariana Grande",
  "Steve Jobs",
  "Tom Cruise",
  "Tom Hanks",
  "Beyoncé Knowles",
  "Michael Jordan",
  "LeBron James",
  "Barack Obama",
  "Dwayne Johnson",
  "Selena Gomez",
  "Mark Zuckerberg",
  "Stephen King",
  "Meryl Streep",
  "David Beckham",
  "Angelina Jolie",
  "Will Smith",
  "Stephen Hawking",
  "Johnny Depp",
  "Albert Einstein",
];

// Combine all category phrases
const allCategoryPhrases = {
  [PhraseCategory.MOVIES]: moviePhrases,
  [PhraseCategory.MUSIC]: musicPhrases,
  [PhraseCategory.SPORTS]: sportsPhrases,
  [PhraseCategory.FOOD]: foodPhrases,
  [PhraseCategory.PLACES]: placesPhrases,
  [PhraseCategory.PEOPLE]: peoplePhrases,
  [PhraseCategory.TECHNOLOGY]: techPhrases,
  [PhraseCategory.HISTORY]: historyPhrases,
  [PhraseCategory.ENTERTAINMENT]: entertainmentPhrases,
  [PhraseCategory.NATURE]: naturePhrases
};

// All phrases combined for Everything categories
const allPhrases = Object.values(allCategoryPhrases).flat();

export const phrases: string[] = allPhrases;

// Export categorized phrases for category selection
export const categorizedPhrases = allCategoryPhrases;

// Get phrases by category
export function getPhrasesByCategory(category: PhraseCategory): string[] {
  if (category === PhraseCategory.EVERYTHING) {
    return allPhrases;
  }
  if (category === PhraseCategory.EVERYTHING_PLUS) {
    return allPhrases;
  }
  return categorizedPhrases[category] || [];
}

export const DEFAULT_CATEGORIES: PhraseCategory[] = [
  PhraseCategory.MOVIES,
  PhraseCategory.MUSIC,
  PhraseCategory.SPORTS,
  PhraseCategory.FOOD,
  PhraseCategory.PLACES,
  PhraseCategory.PEOPLE,
  PhraseCategory.TECHNOLOGY,
  PhraseCategory.HISTORY,
  PhraseCategory.ENTERTAINMENT,
  PhraseCategory.NATURE,
];
