/**
 * Collection of phrases for the Words on Phone game
 */
const phrases: string[] = [
  // Common English idioms
  'A blessing in disguise',
  'A dime a dozen',
  'A piece of cake',
  'Actions speak louder than words',
  'Add insult to injury',
  'Against all odds',
  'All ears',
  'Back to square one',
  'Barking up the wrong tree',
  'Beat around the bush',
  'Beating a dead horse',
  'Bite off more than you can chew',
  'Break a leg',
  'Costs an arm and a leg',
  'Cut corners',
  'Cut to the chase',
  'Cry over spilled milk',
  'Don\'t judge a book by its cover',
  'Easier said than done',
  'Every cloud has a silver lining',
  'Get your act together',
  'Give the benefit of the doubt',
  'Hit the nail on the head',
  'It\'s not rocket science',
  'Jump on the bandwagon',
  'Let the cat out of the bag',
  'Miss the boat',
  'Once in a blue moon',
  'Pull yourself together',
  'Speak of the devil',
  'Steal someone\'s thunder',
  'Take it with a grain of salt',
  'The ball is in your court',
  'The best of both worlds',
  'The early bird catches the worm',
  'The elephant in the room',
  'The last straw',
  'The whole nine yards',
  'Time flies when you\'re having fun',
  'Under the weather',
  'When pigs fly',
  
  // Famous sayings
  'All that glitters is not gold',
  'All\'s well that ends well',
  'Better late than never',
  'Don\'t count your chickens before they hatch',
  'Early to bed and early to rise makes a man healthy, wealthy, and wise',
  'Honesty is the best policy',
  'Keep your friends close and your enemies closer',
  'Laughter is the best medicine',
  'Money can\'t buy happiness',
  'Practice makes perfect',
  'Rome wasn\'t built in a day',
  'The pen is mightier than the sword',
  'Time is money',
  'You can\'t teach an old dog new tricks',
  
  // Common actions
  'Cooking dinner',
  'Dancing like nobody\'s watching',
  'Driving a car',
  'Playing basketball',
  'Riding a bicycle',
  'Running a marathon',
  'Singing in the shower',
  'Swimming in the ocean',
  'Taking a selfie',
  'Typing on a keyboard',
];

export default phrases; 